services:
  - type: web
    name: zachitoWEB
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: RABOiEuvtKtV6TK3teiDiiVugjgzsWrvtcqJIj6i5Ug=
